# 机器学习

In [8]:
import pandas as pd

In [9]:
team_info = pd.read_csv('inputData/evl_team_score.csv')

In [10]:
team_info

,team_name,Tm_FGA,Tm_FTA,Tm_FG,Tm_ORB,Tm_DRB,Tm_TOV,Opp_FGA,Opp_FTA,Opp_FG,Opp_ORB,Opp_DRB,Opp_TOV
0,俄克拉荷马雷霆,87.233333,22.766667,39.200000,10.266667,33.766667,15.600000,88.100000,23.000000,40.766667,34.233333,34.233333,14.666667
1,底特律活塞,87.366667,24.633333,38.933333,9.633333,34.733333,11.666667,87.800000,18.933333,40.833333,35.566667,35.566667,12.833333
2,奥兰多魔术,86.366667,20.966667,39.133333,10.466667,34.033333,13.466667,84.766667,23.233333,37.933333,33.766667,33.766667,13.400000
3,芝加哥公牛,87.300000,20.366667,39.133333,9.566667,33.933333,13.200000,87.200000,21.600000,40.366667,35.600000,35.600000,12.833333
4,犹他爵士,87.500000,22.633333,41.133333,9.966667,32.700000,13.700000,86.600000,23.600000,40.700000,33.700000,33.700000,14.800000
5,洛杉矶湖人,87.933333,20.766667,39.066667,10.200000,34.433333,13.300000,87.500000,20.466667,40.900000,35.433333,35.433333,12.966667
6,夏洛特黄蜂,85.766667,22.466667,39.733333,9.533333,33.333333,13.033333,88.100000,19.966667,41.833333,33.866667,33.866667,12.333333
7,布鲁克林篮网,88.033333,20.700000,39.300000,10.866667,33.900000,12.400000,84.600000,21.233333,39.166667,34.666667,34.666667,13.333333
8,华盛顿奇才,85.933333,20.700000,40.466667,9.333333,33.200000,13.133333,85.000000,21.400000,38.700000,33.166667,33.166667,14.666667
9,密尔沃基雄鹿,85.300000,23.000000,40.633333,8.833333,34.500000,13.266667,86.700000,22.500000,39.166667,33.400000,33.400000,13.900000
10,波特兰开拓者,87.133333,24.300000,38.733333,9.766667,35.100000,14.833333,90.866667,23.766667,41.833333,35.900000,35.900000,12.566667
11,孟菲斯灰熊,86.833333,21.100000,39.633333,9.433333,34.233333,12.866667,86.266667,23.033333,38.500000,34.433333,34.433333,13.900000
12,迈阿密热火,88.166667,21.366667,39.533333,11.033333,33.666667,13.633333,87.800000,23.700000,40.366667,34.233333,34.233333,12.666667
13,费城76人,86.633333,24.233333,39.966667,10.533333,35.466667,15.500000,88.333333,25.433333,39.733333,33.266667,33.266667,13.533333
14,丹佛掘金,86.966667,22.833333,40.866667,10.000000,34.066667,12.633333,86.033333,23.300000,38.633333,32.933333,32.933333,14.000000
15,波士顿凯尔特人,87.333333,21.133333,43.300000,9.200000,35.500000,14.366667,90.000000,23.233333,39.766667,32.266667,32.266667,13.766667
16,密尔沃基雄鹿,85.300000,26.666667,40.300000,9.600000,34.533333,13.466667,88.100000,24.100000,40.166667,33.433333,33.433333,12.933333
17,休斯顿火箭,88.766667,23.100000,40.866667,10.733333,34.733333,15.000000,89.600000,23.066667,41.500000,34.800000,34.800000,13.733333
18,多伦多猛龙,87.633333,24.266667,39.500000,10.466667,32.666667,15.066667,87.666667,27.066667,41.500000,34.800000,34.800000,14.200000
19,新奥尔良鹈鹕,87.100000,20.933333,39.933333,9.733333,32.766667,13.400000,85.433333,23.366667,39.766667,34.766667,34.766667,14.100000
20,圣安东尼奥马刺,88.133333,22.500000,41.300000,11.600000,34.166667,13.900000,87.166667,21.533333,41.000000,32.000000,32.000000,12.633333
21,明尼苏达森林狼,87.266667,24.333333,40.733333,11.066667,32.066667,12.633333,86.000000,21.933333,40.633333,32.266667,32.266667,14.200000
22,印第安纳步行者,89.766667,25.066667,40.666667,12.466667,34.100000,13.933333,85.933333,23.166667,39.500000,33.300000,33.300000,14.833333
23,洛杉矶快船,87.900000,22.666667,40.366667,10.700000,35.033333,13.133333,87.333333,23.800000,39.533333,33.400000,33.400000,12.233333
24,亚特兰大老鹰,82.833333,23.233333,38.533333,9.433333,34.800000,13.933333,84.433333,21.100000,37.800000,32.566667,32.566667,13.166667
25,纽约尼克斯,85.000000,20.866667,37.700000,8.700000,32.966667,12.200000,83.966667,21.900000,39.100000,35.700000,35.700000,13.500000
26,克里夫兰骑士,86.233333,25.366667,39.433333,10.033333,33.266667,13.500000,86.966667,21.866667,40.400000,33.700000,33.700000,14.300000
27,菲尼克斯太阳,83.633333,22.500000,37.000000,9.700000,31.966667,13.366667,80.800000,26.166667,36.500000,33.766667,33.766667,14.100000
28,金州勇士,89.100000,22.266667,41.833333,9.466667,35.666667,13.766667,91.266667,21.566667,41.700000,35.700000,35.700000,13.433333
29,萨克拉门托国王,85.800000,21.300000,40.200000,9.833333,34.366667,12.466667,85.800000,20.000000,38.933333,33.233333,33.233333,13.100000

In [11]:
team_info['t1'] = team_info['Tm_FGA']+0.4*team_info['Tm_FTA']-1.07*(team_info['Tm_ORB'] / (team_info['Tm_ORB']+team_info['Opp_DRB']))*(team_info['Tm_FGA']-team_info['Tm_FG'])+team_info['Tm_TOV']

In [12]:
team_info['t2'] = team_info['Opp_FGA']+0.4*team_info['Opp_FTA']-1.07*(team_info['Opp_ORB'] / (team_info['Opp_ORB']+team_info['Tm_DRB']))*(team_info['Opp_FGA']-team_info['Opp_FG'])+team_info['Opp_TOV']

In [13]:
team_info['score'] = (team_info['t1']+team_info['t2'])*0.5

In [16]:
tmp_df = team_info[['team_name','score']].sort_values('score',ascending=False)

In [18]:
team_name = tmp_df['team_name']

In [29]:
import numpy as np
a = list(np.array(team_name))

In [33]:
a

['金州勇士',
 '休斯顿火箭',
 '多伦多猛龙',
 '波士顿凯尔特人',
 '波特兰开拓者',
 '费城76人',
 '俄克拉荷马雷霆',
 '印第安纳步行者',
 '犹他爵士',
 '密尔沃基雄鹿',
 '克里夫兰骑士',
 '密尔沃基雄鹿',
 '圣安东尼奥马刺',
 '迈阿密热火',
 '洛杉矶快船',
 '丹佛掘金',
 '新奥尔良鹈鹕',
 '明尼苏达森林狼',
 '洛杉矶湖人',
 '孟菲斯灰熊',
 '芝加哥公牛',
 '底特律活塞',
 '夏洛特黄蜂',
 '华盛顿奇才',
 '奥兰多魔术',
 '布鲁克林篮网',
 '萨克拉门托国王',
 '亚特兰大老鹰',
 '纽约尼克斯',
 '菲尼克斯太阳']